resource_group_name = "cooey-terraform-rg"
resource_group_location = "East US"
location = "East US"
vnet_name = "terravnet"
network_address_space = "10.0.0.0/16"
aks_subnet_address_prefix = "10.0.1.0/24"
aks_subnet_address_name = "terrasubnet"
vnet_environment = "development"